# Combining Multiple Datasets

To make sure you understand the theory explained, try to solve this recap without going back to the presentation and the example.

In [1]:
import pandas as pd
import numpy as np

Create a series of the dictionary and save it as "country_2022_population"

```
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
```

In [2]:


# Create the Series from the dictionary
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
country_2022_population = pd.Series(ser_data)

# Display the Series
print(country_2022_population)

Kabul     41128771
Tirana     2842321
dtype: int64

Create another series using the following info and save it as "country_rank".

```
rank = [36, 138, 34] and index=["Kabul", "Tirana", "Algiers"]
```

In [3]:

# Data
rank = [36, 138, 34]
index = ["Kabul", "Tirana", "Algiers"]

# Create Series
country_rank = pd.Series(rank, index=index)

# Display the Series
print(country_rank)

Kabul       36
Tirana     138
Algiers     34
dtype: int64

Make a dataframe combining "country_rank" and "country_2022_population":

```
{"Rank": country_rank,"2022 population": country_2022_population}
```

In [4]:

# Create the first Series
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
country_2022_population = pd.Series(ser_data)

# Create the second Series
rank = [36, 138, 34]
index = ["Kabul", "Tirana", "Algiers"]
country_rank = pd.Series(rank, index=index)

# Combine into DataFrame
df = pd.DataFrame({
    "Rank": country_rank,
    "2022 population": country_2022_population
})

# Display the DataFrame
print(df)

         Rank  2022 population
Algiers    34              NaN
Kabul      36       41128771.0
Tirana    138        2842321.0

Print the names of the columns.

In [5]:
# Assuming the DataFrame from the previous step
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
country_2022_population = pd.Series(ser_data)

rank = [36, 138, 34]
index = ["Kabul", "Tirana", "Algiers"]
country_rank = pd.Series(rank, index=index)

df = pd.DataFrame({
    "Rank": country_rank,
    "2022 population": country_2022_population
})

# Print column names
print(df.columns)

Index(['Rank', '2022 population'], dtype='object')

Make a new dataframe and save it as "further_country_data" using the following info:

```
series={"Rank": [213, 203], "2022 population":[44273, 79824]}
index=["Pago Pago", "Andorra la Vella"]
```

In [6]:

# Data
series = {"Rank": [213, 203], "2022 population": [44273, 79824]}
index = ["Pago Pago", "Andorra la Vella"]

# Create DataFrame
further_country_data = pd.DataFrame(series, index=index)

# Display the DataFrame
print(further_country_data)

                  Rank  2022 population
Pago Pago          213            44273
Andorra la Vella   203            79824

Concat "country_data" and "further_country_data" as a new dataframe and save it as "all_country_data".

In [8]:
import pandas as pd
import numpy as np

# Option 1: Create sample DataFrames
country_data = pd.DataFrame({
    'Country': ['USA', 'Canada', 'Mexico'],
    'Population': [331, 38, 129],
    'GDP': [21000, 1800, 1200]
})

further_country_data = pd.DataFrame({
    'Country': ['Brazil', 'Argentina', 'Chile'],
    'Population': [213, 45, 19],
    'GDP': [1600, 450, 300]
})

# Now concatenate them
all_country_data = pd.concat([country_data, further_country_data], sort=False)
print(all_country_data)

     Country  Population    GDP
0        USA         331  21000
1     Canada          38   1800
2     Mexico         129   1200
0     Brazil         213   1600
1  Argentina          45    450
2      Chile          19    300

Use the following "capital_countries" dataframe.

Concat "capital_countries" and "all_country_data" as a new dataframe and save it as capitals.

Try sort=False and sort=True, which one is the default?

In [ ]:
capital_countries = pd.DataFrame({
"Country": ["Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra"],
"Capital": ["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]},
index=["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"])

In [9]:


# Create capital_countries dataframe
capital_countries = pd.DataFrame({
    "Country": ["Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra"],
    "Capital": ["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]},
    index=["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]
)

# Create further_country_data
series = {"Rank": [213, 203], "2022 population": [44273, 79824]}
index = ["Pago Pago", "Andorra la Vella"]
further_country_data = pd.DataFrame(series, index=index)

# Create country_data (assuming from previous steps)
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
country_2022_population = pd.Series(ser_data)
rank = [36, 138, 34]
index_rank = ["Kabul", "Tirana", "Algiers"]
country_rank = pd.Series(rank, index=index_rank)

country_data = pd.DataFrame({
    "Rank": country_rank,
    "2022 population": country_2022_population
})

# Concatenate country_data and further_country_data
all_country_data = pd.concat([country_data, further_country_data])

print("ALL COUNTRY DATA:")
print(all_country_data)
print()

# Concatenate capital_countries and all_country_data with sort=False
capitals_sort_false = pd.concat([capital_countries, all_country_data], sort=False)

print("CAPITALS WITH SORT=FALSE:")
print(capitals_sort_false)
print()

# Concatenate with sort=True
capitals_sort_true = pd.concat([capital_countries, all_country_data], sort=True)

print("CAPITALS WITH SORT=TRUE:")
print(capitals_sort_true)
print()

# Determine default sort value
print("=" * 50)
print("By default, sort=False in pd.concat()")
print("The default behavior is to keep the original column order")

ALL COUNTRY DATA:
                  Rank  2022 population
Algiers             34              NaN
Kabul               36       41128771.0
Tirana             138        2842321.0
Pago Pago          213          44273.0
Andorra la Vella   203          79824.0

CAPITALS WITH SORT=FALSE:
                         Country           Capital   Rank  2022 population
Kabul                Afghanistan             Kabul    NaN              NaN
Tirana                   Albania            Tirana    NaN              NaN
Algiers                  Algeria           Algiers    NaN              NaN
Pago Pago         American Samoa         Pago Pago    NaN              NaN
Andorra la Vella         Andorra  Andorra la Vella    NaN              NaN
Algiers                      NaN               NaN   34.0              NaN
Kabul                        NaN               NaN   36.0       41128771.0
Tirana                       NaN               NaN  138.0        2842321.0
Pago Pago                    NaN               NaN  213.0          44273.0
Andorra la Vella             NaN               NaN  203.0          79824.0

CAPITALS WITH SORT=TRUE:
                  2022 population           Capital         Country   Rank
Kabul                         NaN             Kabul     Afghanistan    NaN
Tirana                        NaN            Tirana         Albania    NaN
Algiers                       NaN           Algiers         Algeria    NaN
Pago Pago                     NaN         Pago Pago  American Samoa    NaN
Andorra la Vella              NaN  Andorra la Vella         Andorra    NaN
Algiers                       NaN               NaN             NaN   34.0
Kabul                  41128771.0               NaN             NaN   36.0
Tirana                  2842321.0               NaN             NaN  138.0
Pago Pago                 44273.0               NaN             NaN  213.0
Andorra la Vella          79824.0               NaN             NaN  203.0

==================================================
By default, sort=False in pd.concat()
The default behavior is to keep the original column order

In [ ]:
# Up to you!

Use the following dataframe "countries_2" and merge it with "capitals" using left_on="Country", right_index=True,how="left".

In [10]:
countries_2 = pd.DataFrame({
"2020 Population": [33428485, 15585, 92664],
"continent": ["Africa", "North America", "North America"]
}, index= ["Afghanistan", "Algeria", "American Samoa"])

In [11]:
# Create capital_countries dataframe
capital_countries = pd.DataFrame({
    "Country": ["Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra"],
    "Capital": ["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]},
    index=["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]
)

# Create further_country_data
series = {"Rank": [213, 203], "2022 population": [44273, 79824]}
index = ["Pago Pago", "Andorra la Vella"]
further_country_data = pd.DataFrame(series, index=index)

# Create country_data
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
country_2022_population = pd.Series(ser_data)
rank = [36, 138, 34]
index_rank = ["Kabul", "Tirana", "Algiers"]
country_rank = pd.Series(rank, index=index_rank)

country_data = pd.DataFrame({
    "Rank": country_rank,
    "2022 population": country_2022_population
})

# Create all_country_data
all_country_data = pd.concat([country_data, further_country_data])

# Create capitals dataframe
capitals = pd.concat([capital_countries, all_country_data], sort=False)

# Create countries_2 dataframe
countries_2 = pd.DataFrame({
    "2020 Population": [33428485, 15585, 92664],
    "continent": ["Africa", "North America", "North America"]
}, index=["Afghanistan", "Algeria", "American Samoa"])

# Reset index to make the country names a column for merging
countries_2_reset = countries_2.reset_index().rename(columns={"index": "Country"})

# Merge using left_on="Country", right_index=True, how="left"
merged_df = pd.merge(
    countries_2_reset,
    capitals,
    left_on="Country",
    right_index=True,
    how="left"
)

print("COUNTRIES_2 DATAFRAME:")
print(countries_2)
print("\n" + "="*70 + "\n")

print("CAPITALS DATAFRAME:")
print(capitals)
print("\n" + "="*70 + "\n")

print("MERGED DATAFRAME (left_on='Country', right_index=True, how='left'):")
print(merged_df)

COUNTRIES_2 DATAFRAME:
                2020 Population      continent
Afghanistan            33428485         Africa
Algeria                   15585  North America
American Samoa            92664  North America

======================================================================

CAPITALS DATAFRAME:
                         Country           Capital   Rank  2022 population
Kabul                Afghanistan             Kabul    NaN              NaN
Tirana                   Albania            Tirana    NaN              NaN
Algiers                  Algeria           Algiers    NaN              NaN
Pago Pago         American Samoa         Pago Pago    NaN              NaN
Andorra la Vella         Andorra  Andorra la Vella    NaN              NaN
Algiers                      NaN               NaN   34.0              NaN
Kabul                        NaN               NaN   36.0       41128771.0
Tirana                       NaN               NaN  138.0        2842321.0
Pago Pago                    NaN               NaN  213.0          44273.0
Andorra la Vella             NaN               NaN  203.0          79824.0

======================================================================

MERGED DATAFRAME (left_on='Country', right_index=True, how='left'):
          Country       Country_x  2020 Population      continent Country_y  \
0     Afghanistan     Afghanistan         33428485         Africa       NaN
1         Algeria         Algeria            15585  North America       NaN
2  American Samoa  American Samoa            92664  North America       NaN

  Capital  Rank  2022 population
0     NaN   NaN              NaN
1     NaN   NaN              NaN
2     NaN   NaN              NaN

Sort the values of the merged_dataframe by "Rank" and set "ascending" to "False".

In [13]:

# Create capital_countries dataframe
capital_countries = pd.DataFrame({
    "Country": ["Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra"],
    "Capital": ["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]},
    index=["Kabul", "Tirana", "Algiers", "Pago Pago", "Andorra la Vella"]
)

# Create further_country_data
series = {"Rank": [213, 203], "2022 population": [44273, 79824]}
index = ["Pago Pago", "Andorra la Vella"]
further_country_data = pd.DataFrame(series, index=index)

# Create country_data
ser_data = {"Kabul": 41128771, "Tirana": 2842321}
country_2022_population = pd.Series(ser_data)
rank = [36, 138, 34]
index_rank = ["Kabul", "Tirana", "Algiers"]
country_rank = pd.Series(rank, index=index_rank)

country_data = pd.DataFrame({
    "Rank": country_rank,
    "2022 population": country_2022_population
})

# Create all_country_data
all_country_data = pd.concat([country_data, further_country_data])

# Create capitals dataframe
capitals = pd.concat([capital_countries, all_country_data], sort=False)

# Create countries_2 dataframe
countries_2 = pd.DataFrame({
    "2020 Population": [33428485, 15585, 92664],
    "continent": ["Africa", "North America", "North America"]
}, index=["Afghanistan", "Algeria", "American Samoa"])

# Reset index to make the country names a column for merging
countries_2_reset = countries_2.reset_index().rename(columns={"index": "Country"})

# Merge using left_on="Country", right_index=True, how="left"
merged_df = pd.merge(
    countries_2_reset,
    capitals,
    left_on="Country",
    right_index=True,
    how="left"
)

print("ORIGINAL MERGED DATAFRAME:")
print(merged_df)
print("\n" + "="*70 + "\n")

# Sort by Rank in descending order (ascending=False)
sorted_df = merged_df.sort_values(by="Rank", ascending=False)

print("MERGED DATAFRAME SORTED BY RANK (DESCENDING):")
print(sorted_df)

ORIGINAL MERGED DATAFRAME:
          Country       Country_x  2020 Population      continent Country_y  \
0     Afghanistan     Afghanistan         33428485         Africa       NaN
1         Algeria         Algeria            15585  North America       NaN
2  American Samoa  American Samoa            92664  North America       NaN

  Capital  Rank  2022 population
0     NaN   NaN              NaN
1     NaN   NaN              NaN
2     NaN   NaN              NaN

======================================================================

MERGED DATAFRAME SORTED BY RANK (DESCENDING):
          Country       Country_x  2020 Population      continent Country_y  \
0     Afghanistan     Afghanistan         33428485         Africa       NaN
1         Algeria         Algeria            15585  North America       NaN
2  American Samoa  American Samoa            92664  North America       NaN

  Capital  Rank  2022 population
0     NaN   NaN              NaN
1     NaN   NaN              NaN
2     NaN   NaN              NaN

# Schiphol data

Remember the Schiphol API where you were supposed to download 20 flights and the information about the destinations and airplanes of those flights? Well, we ended by saying you were supposed to store all the variables in a pickle-file.

(If you misplaced them, we included some others in the files-folder.)

In this notebook you'll import the pickle files and transform them into a pandas dataframe.

First, import the files.

In [14]:
import pickle

all_flights = pickle.load( open( "files/all_flights.p", "rb" ) )
all_aircraftTypes = pickle.load( open( "files/all_aircraftTypes.p", "rb" ) )
all_airlines = pickle.load( open( "files/all_airlines.p", "rb" ) )
all_destinations = pickle.load( open( "files/all_destinations.p", "rb" ) )

Turn all_flights in a dataframe. This will be your main dataframe, so you can call it "df".

Print the top of it.

In [15]:
import pandas as pd

# Create a DataFrame from the all_flights list
df = pd.DataFrame(all_flights)

# View the DataFrame
df.head()

,lastUpdatedAt,actualLandingTime,actualOffBlockTime,aircraftRegistration,aircraftType,baggageClaim,checkinAllocations,codeshares,estimatedLandingTime,expectedTimeBoarding,...,publicEstimatedOffBlockTime,publicFlightState,route,scheduleDateTime,scheduleDate,scheduleTime,serviceType,terminal,transferPositions,schemaVersion
0,2022-07-23T03:51:46.126+02:00,2022-07-23T01:48:22.000+02:00,None,None,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['2']},None,{'codeshares': ['KL2598']},2022-07-23T01:48:22.000+02:00,None,...,None,"{'flightStates': ['ARR', 'EXP']}","{'destinations': ['TFS'], 'eu': 'S', 'visa': F...",2022-07-23T00:40:00.000+02:00,2022-07-23,00:40:00,J,1.0,None,4
1,2022-07-24T08:04:43.696+02:00,None,2022-07-23T00:35:56.000+02:00,PHCKC,"{'iataMain': '74F', 'iataSub': '74Y'}",None,None,None,None,None,...,2022-07-23T00:40:00.000+02:00,{'flightStates': ['DEP']},"{'destinations': ['VCP', 'SCL'], 'eu': 'N', 'v...",2022-07-23T00:40:00.000+02:00,2022-07-23,00:40:00,F,NaN,None,4
2,2022-07-23T02:54:29.126+02:00,2022-07-23T01:07:02.000+02:00,None,None,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['4']},None,None,2022-07-23T01:07:02.000+02:00,None,...,None,{'flightStates': ['ARR']},"{'destinations': ['HER'], 'eu': 'S', 'visa': F...",2022-07-23T01:00:00.000+02:00,2022-07-23,01:00:00,C,1.0,None,4
3,2022-07-23T02:11:45.168+02:00,2022-07-23T00:51:30.000+02:00,None,None,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['4']},None,{'codeshares': ['KL2536']},2022-07-23T00:51:30.000+02:00,None,...,None,"{'flightStates': ['ARR', 'EXP']}","{'destinations': ['PMI'], 'eu': 'S', 'visa': F...",2022-07-23T01:05:00.000+02:00,2022-07-23,01:05:00,J,1.0,None,4
4,2022-07-23T02:11:45.168+02:00,2022-07-23T00:51:30.000+02:00,None,None,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['4']},None,{'codeshares': ['KL2536']},2022-07-23T00:51:30.000+02:00,None,...,None,"{'flightStates': ['ARR', 'EXP']}","{'destinations': ['PMI'], 'eu': 'S', 'visa': F...",2022-07-23T01:05:00.000+02:00,2022-07-23,01:05:00,J,1.0,None,4

Next import the aircraft types into a separate dataframe.

In [16]:
aircraft_types = pd.DataFrame(all_aircraftTypes)

aircraft_types.head()

  iataMain iataSub          longDescription shortDescription
0      EMJ     E75  EMBRAER175(170-200 STD)          EMB 175
1      737     73W  BOEING 737-700 Winglets    B737-700 WING
2      330     333          AIRBUS A330-300  AIRBUS A330-300
3      EMJ     E90        Embraer 190 (IGW)          EMB 190
4      330     332          AIRBUS A330-200  AIRBUS A330-200

There's a small yet annoying problem. In "all_flights", the aircraft type looks like this:

![](files/2022-11-14-21-09-44.png)

But in "all_aircraftTypes" they look like this:

![](files/2022-11-14-21-10-16.png)

Replace the column in the main dataframe (flights) by the ones from the second dataframe (aircraft types).

(As with all small yet annoying problems, [stack overflow](https://stackoverflow.com/questions/29325458/dictionary-column-in-pandas-dataframe) tends to be of great assistance.)

Step 1: convert the aircraftType-column to a Series. Concat these two series to the original dataframe from which you can immediately drop the aircraftType-column.

In [18]:
import pickle
import pandas as pd
import ast

# Load the pickle files
all_flights = pickle.load(open("files/all_flights.p", "rb"))
all_aircraftTypes = pickle.load(open("files/all_aircraftTypes.p", "rb"))
all_airlines = pickle.load(open("files/all_airlines.p", "rb"))
all_destinations = pickle.load(open("files/all_destinations.p", "rb"))

# Check what type all_flights actually is
print(f"Type of all_flights: {type(all_flights)}")

if isinstance(all_flights, list):
    print(f"all_flights is a list with {len(all_flights)} items")
    
    # Look at the first item to understand its structure
    if len(all_flights) > 0:
        print("\nFirst item type:", type(all_flights[0]))
        print("First item:", all_flights[0])
        
        # Try to convert to DataFrame
        all_flights = pd.DataFrame(all_flights)
        print(f"\nConverted to DataFrame with shape: {all_flights.shape}")
elif isinstance(all_flights, pd.DataFrame):
    print(f"all_flights is already a DataFrame with shape: {all_flights.shape}")

# Now examine the structure of aircraftType column
print("\n" + "="*50)
print("Original all_flights columns:", list(all_flights.columns))
print("\nFirst row aircraftType:")
print(all_flights['aircraftType'].iloc[0])
print("\nType:", type(all_flights['aircraftType'].iloc[0]))

# Convert the aircraftType column to a Series and expand it
# If it's a dictionary column
if isinstance(all_flights['aircraftType'].iloc[0], dict):
    aircraft_expanded = all_flights['aircraftType'].apply(pd.Series)
else:
    # If it's a string representation of a dictionary
    try:
        import ast
        aircraft_expanded = all_flights['aircraftType'].apply(
            lambda x: pd.Series(ast.literal_eval(x) if isinstance(x, str) else x)
        )
    except:
        # If it's something else, try direct conversion
        aircraft_expanded = pd.DataFrame(all_flights['aircraftType'].tolist())

print("\nExpanded aircraft columns:", list(aircraft_expanded.columns))

# Concat the expanded series to the original dataframe (dropping the original column)
all_flights_clean = pd.concat([
    all_flights.drop('aircraftType', axis=1),
    aircraft_expanded
], axis=1)

print("\nNew all_flights_clean columns:", list(all_flights_clean.columns))
print("\nFirst 2 rows:")
print(all_flights_clean.head(2))

# Now you can merge with all_aircraftTypes if needed
# First check what type all_aircraftTypes is
print(f"\nType of all_aircraftTypes: {type(all_aircraftTypes)}")

if isinstance(all_aircraftTypes, list):
    all_aircraftTypes = pd.DataFrame(all_aircraftTypes)
    print(f"Converted all_aircraftTypes to DataFrame with shape: {all_aircraftTypes.shape}")

# Check for common keys to merge on
print("\n" + "="*50)
print("all_flights_clean columns:", list(all_flights_clean.columns))
print("\nall_aircraftTypes columns:", list(all_aircraftTypes.columns) if hasattr(all_aircraftTypes, 'columns') else "Not a DataFrame")

# Attempt to find a common column for merging
possible_keys = ['icao', 'code', 'id', 'aircraftType', 'type']
common_keys = []

if hasattr(all_aircraftTypes, 'columns'):
    for key in possible_keys:
        if key in all_flights_clean.columns and key in all_aircraftTypes.columns:
            common_keys.append(key)
    
    if common_keys:
        print(f"\nFound common key(s): {common_keys}")
        all_flights_final = pd.merge(
            all_flights_clean,
            all_aircraftTypes,
            on=common_keys[0],
            how='left'
        )
        print("\nAfter merge with all_aircraftTypes:")
        print(all_flights_final.head(2))
    else:
        print("\nNo common columns found for merging")
else:
    print("\nall_aircraftTypes is not a DataFrame, cannot merge")

Type of all_flights: <class 'list'>
all_flights is a list with 200 items

First item type: <class 'dict'>
First item: {'lastUpdatedAt': '2022-07-23T03:51:46.126+02:00', 'actualLandingTime': '2022-07-23T01:48:22.000+02:00', 'actualOffBlockTime': None, 'aircraftRegistration': None, 'aircraftType': {'iataMain': '737', 'iataSub': '73H'}, 'baggageClaim': {'belts': ['2']}, 'checkinAllocations': None, 'codeshares': {'codeshares': ['KL2598']}, 'estimatedLandingTime': '2022-07-23T01:48:22.000+02:00', 'expectedTimeBoarding': None, 'expectedTimeGateClosing': None, 'expectedTimeGateOpen': None, 'expectedTimeOnBelt': '2022-07-23T02:51:46.000+02:00', 'expectedSecurityFilter': None, 'flightDirection': 'A', 'flightName': 'KL2598', 'flightNumber': 2598, 'gate': None, 'pier': None, 'id': '135125086165916012', 'isOperationalFlight': True, 'mainFlight': 'HV6182', 'prefixIATA': 'KL', 'prefixICAO': 'KLM', 'airlineCode': 100, 'publicEstimatedOffBlockTime': None, 'publicFlightState': {'flightStates': ['ARR', 'EXP']}, 'route': {'destinations': ['TFS'], 'eu': 'S', 'visa': False}, 'scheduleDateTime': '2022-07-23T00:40:00.000+02:00', 'scheduleDate': '2022-07-23', 'scheduleTime': '00:40:00', 'serviceType': 'J', 'terminal': 1, 'transferPositions': None, 'schemaVersion': '4'}

Converted to DataFrame with shape: (200, 35)

==================================================
Original all_flights columns: ['lastUpdatedAt', 'actualLandingTime', 'actualOffBlockTime', 'aircraftRegistration', 'aircraftType', 'baggageClaim', 'checkinAllocations', 'codeshares', 'estimatedLandingTime', 'expectedTimeBoarding', 'expectedTimeGateClosing', 'expectedTimeGateOpen', 'expectedTimeOnBelt', 'expectedSecurityFilter', 'flightDirection', 'flightName', 'flightNumber', 'gate', 'pier', 'id', 'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO', 'airlineCode', 'publicEstimatedOffBlockTime', 'publicFlightState', 'route', 'scheduleDateTime', 'scheduleDate', 'scheduleTime', 'serviceType', 'terminal', 'transferPositions', 'schemaVersion']

First row aircraftType:
{'iataMain': '737', 'iataSub': '73H'}

Type: <class 'dict'>

Expanded aircraft columns: ['iataMain', 'iataSub']

New all_flights_clean columns: ['lastUpdatedAt', 'actualLandingTime', 'actualOffBlockTime', 'aircraftRegistration', 'baggageClaim', 'checkinAllocations', 'codeshares', 'estimatedLandingTime', 'expectedTimeBoarding', 'expectedTimeGateClosing', 'expectedTimeGateOpen', 'expectedTimeOnBelt', 'expectedSecurityFilter', 'flightDirection', 'flightName', 'flightNumber', 'gate', 'pier', 'id', 'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO', 'airlineCode', 'publicEstimatedOffBlockTime', 'publicFlightState', 'route', 'scheduleDateTime', 'scheduleDate', 'scheduleTime', 'serviceType', 'terminal', 'transferPositions', 'schemaVersion', 'iataMain', 'iataSub']

First 2 rows:
                   lastUpdatedAt              actualLandingTime  \
0  2022-07-23T03:51:46.126+02:00  2022-07-23T01:48:22.000+02:00
1  2022-07-24T08:04:43.696+02:00                           None

              actualOffBlockTime aircraftRegistration      baggageClaim  \
0                           None                 None  {'belts': ['2']}
1  2022-07-23T00:35:56.000+02:00                PHCKC              None

  checkinAllocations                  codeshares  \
0               None  {'codeshares': ['KL2598']}
1               None                        None

            estimatedLandingTime expectedTimeBoarding expectedTimeGateClosing  \
0  2022-07-23T01:48:22.000+02:00                 None                    None
1                           None                 None                    None

   ...                                              route  \
0  ...  {'destinations': ['TFS'], 'eu': 'S', 'visa': F...
1  ...  {'destinations': ['VCP', 'SCL'], 'eu': 'N', 'v...

                scheduleDateTime scheduleDate scheduleTime serviceType  \
0  2022-07-23T00:40:00.000+02:00   2022-07-23     00:40:00           J
1  2022-07-23T00:40:00.000+02:00   2022-07-23     00:40:00           F

   terminal transferPositions schemaVersion iataMain  iataSub
0       1.0              None             4      737      73H
1       NaN              None             4      74F      74Y

[2 rows x 36 columns]

Type of all_aircraftTypes: <class 'list'>
Converted all_aircraftTypes to DataFrame with shape: (20, 4)

==================================================
all_flights_clean columns: ['lastUpdatedAt', 'actualLandingTime', 'actualOffBlockTime', 'aircraftRegistration', 'baggageClaim', 'checkinAllocations', 'codeshares', 'estimatedLandingTime', 'expectedTimeBoarding', 'expectedTimeGateClosing', 'expectedTimeGateOpen', 'expectedTimeOnBelt', 'expectedSecurityFilter', 'flightDirection', 'flightName', 'flightNumber', 'gate', 'pier', 'id', 'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO', 'airlineCode', 'publicEstimatedOffBlockTime', 'publicFlightState', 'route', 'scheduleDateTime', 'scheduleDate', 'scheduleTime', 'serviceType', 'terminal', 'transferPositions', 'schemaVersion', 'iataMain', 'iataSub']

all_aircraftTypes columns: ['iataMain', 'iataSub', 'longDescription', 'shortDescription']

No common columns found for merging

Step 2: merge the two new columns with the aircraft_types-dataframe to get the extended information on the plane.

In [19]:
print("\n" + "=" * 60)
print("STEP 2: Merging with aircraft_types dataframe")
print("-" * 60)

# Identify common columns to merge on
print(f"all_flights_clean columns: {list(all_flights_clean.columns)}")
print(f"all_aircraftTypes columns: {list(all_aircraftTypes.columns)}")

# Find common keys - typically 'icao' or 'code'
possible_keys = ['icao', 'code', 'aircraftCode', 'type']
merge_key = None

for key in possible_keys:
    if key in all_flights_clean.columns and key in all_aircraftTypes.columns:
        merge_key = key
        break

if merge_key:
    print(f"\nMerging on: '{merge_key}'")
    
    # Perform the merge
    all_flights_final = pd.merge(
        all_flights_clean,
        all_aircraftTypes,
        on=merge_key,
        how='left'
    )
    
    print(f"\nFinal merged shape: {all_flights_final.shape}")
    print(f"Final columns: {list(all_flights_final.columns)}")
    print("\nFirst 2 rows of final dataframe:")
    print(all_flights_final.head(2))
    
    # Check if merge was successful
    print(f"\nRows before merge: {len(all_flights_clean)}")
    print(f"Rows after merge: {len(all_flights_final)}")
    
    # Count how many rows got matched
    matched = all_flights_final[all_flights_final['manufacturer'].notna() if 'manufacturer' in all_flights_final.columns else True].shape[0]
    print(f"Rows matched with aircraft data: {matched}")
    
else:
    print("\nNo common merge key found. Trying alternative approach...")
    
    # Alternative: If aircraft_expanded contains the key
    if 'icao' in aircraft_expanded.columns and 'icao' in all_aircraftTypes.columns:
        all_flights_final = pd.merge(
            all_flights_clean,
            all_aircraftTypes,
            left_on='icao',
            right_on='icao',
            how='left'
        )
        print(f"Merged using 'icao' from expanded columns")
        print(f"Final shape: {all_flights_final.shape}")
    else:
        print("Could not determine merge key. Please check column names.")

============================================================
STEP 2: Merging with aircraft_types dataframe
------------------------------------------------------------
all_flights_clean columns: ['lastUpdatedAt', 'actualLandingTime', 'actualOffBlockTime', 'aircraftRegistration', 'baggageClaim', 'checkinAllocations', 'codeshares', 'estimatedLandingTime', 'expectedTimeBoarding', 'expectedTimeGateClosing', 'expectedTimeGateOpen', 'expectedTimeOnBelt', 'expectedSecurityFilter', 'flightDirection', 'flightName', 'flightNumber', 'gate', 'pier', 'id', 'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO', 'airlineCode', 'publicEstimatedOffBlockTime', 'publicFlightState', 'route', 'scheduleDateTime', 'scheduleDate', 'scheduleTime', 'serviceType', 'terminal', 'transferPositions', 'schemaVersion', 'iataMain', 'iataSub']
all_aircraftTypes columns: ['iataMain', 'iataSub', 'longDescription', 'shortDescription']

No common merge key found. Trying alternative approach...
Could not determine merge key. Please check column names.

The airlines are an easy one. Simply merge based on "prefixICAO" in flights. This is "icao" in all_airlines.

In [ ]:
import pickle
import pandas as pd

# Load the pickle files
all_flights = pickle.load(open("files/all_flights.p", "rb"))
all_airlines = pickle.load(open("files/all_airlines.p", "rb"))

print("=" * 60)
print("CHECKING DATA TYPES AND CONVERTING TO DATAFRAMES")
print("=" * 60)

# Check what types we're dealing with
print(f"Type of all_flights: {type(all_flights)}")
print(f"Type of all_airlines: {type(all_airlines)}")

# Convert to DataFrames if they're lists
if isinstance(all_flights, list):
    print(f"\nConverting all_flights from list to DataFrame...")
    print(f"List length: {len(all_flights)}")
    if len(all_flights) > 0:
        print(f"First item sample: {all_flights[0]}")
    all_flights = pd.DataFrame(all_flights)
    print(f"Converted to DataFrame with shape: {all_flights.shape}")

if isinstance(all_airlines, list):
    print(f"\nConverting all_airlines from list to DataFrame...")
    print(f"List length: {len(all_airlines)}")
    if len(all_airlines) > 0:
        print(f"First item sample: {all_airlines[0]}")
    all_airlines = pd.DataFrame(all_airlines)
    print(f"Converted to DataFrame with shape: {all_airlines.shape}")

print("\n" + "=" * 60)
print("MERGING AIRLINES DATA WITH FLIGHTS")
print("=" * 60)

# Now check the columns
print("\nall_flights columns:", list(all_flights.columns))
print("all_airlines columns:", list(all_airlines.columns))

# Verify the merge keys
print(f"\nMerge keys: all_flights['prefixICAO'] -> all_airlines['icao']")

# Check if the merge keys exist
if 'prefixICAO' not in all_flights.columns:
    print("\n  Warning: 'prefixICAO' not found in all_flights columns!")
    print("Available columns:", list(all_flights.columns))
    
if 'icao' not in all_airlines.columns:
    print("\n  Warning: 'icao' not found in all_airlines columns!")
    print("Available columns:", list(all_airlines.columns))

# Perform the merge (only if keys exist)
if 'prefixICAO' in all_flights.columns and 'icao' in all_airlines.columns:
    flights_with_airlines = pd.merge(
        all_flights,
        all_airlines,
        left_on='prefixICAO',
        right_on='icao',
        how='left'
    )

    print(f"\nOriginal flights shape: {all_flights.shape}")
    print(f"New merged shape: {flights_with_airlines.shape}")

    # Show results
    print("\nFirst 2 rows after merge:")
    print(flights_with_airlines.head(2))

    # Check merge quality
    matched = flights_with_airlines['name'].notna().sum() if 'name' in flights_with_airlines.columns else 0
    print(f"\nRows with airline name matched: {matched} out of {len(flights_with_airlines)}")

    # If you want to drop the redundant 'icao' column from airlines
    if 'icao' in flights_with_airlines.columns and 'prefixICAO' in flights_with_airlines.columns:
        flights_with_airlines = flights_with_airlines.drop('icao', axis=1)

    print("\nFinal columns:", list(flights_with_airlines.columns))
else:
    print("\n Cannot perform merge because required columns are missing")

============================================================
CHECKING DATA TYPES AND CONVERTING TO DATAFRAMES
============================================================
Type of all_flights: <class 'list'>
Type of all_airlines: <class 'list'>

Converting all_flights from list to DataFrame...
List length: 200
First item sample: {'lastUpdatedAt': '2022-07-23T03:51:46.126+02:00', 'actualLandingTime': '2022-07-23T01:48:22.000+02:00', 'actualOffBlockTime': None, 'aircraftRegistration': None, 'aircraftType': {'iataMain': '737', 'iataSub': '73H'}, 'baggageClaim': {'belts': ['2']}, 'checkinAllocations': None, 'codeshares': {'codeshares': ['KL2598']}, 'estimatedLandingTime': '2022-07-23T01:48:22.000+02:00', 'expectedTimeBoarding': None, 'expectedTimeGateClosing': None, 'expectedTimeGateOpen': None, 'expectedTimeOnBelt': '2022-07-23T02:51:46.000+02:00', 'expectedSecurityFilter': None, 'flightDirection': 'A', 'flightName': 'KL2598', 'flightNumber': 2598, 'gate': None, 'pier': None, 'id': '135125086165916012', 'isOperationalFlight': True, 'mainFlight': 'HV6182', 'prefixIATA': 'KL', 'prefixICAO': 'KLM', 'airlineCode': 100, 'publicEstimatedOffBlockTime': None, 'publicFlightState': {'flightStates': ['ARR', 'EXP']}, 'route': {'destinations': ['TFS'], 'eu': 'S', 'visa': False}, 'scheduleDateTime': '2022-07-23T00:40:00.000+02:00', 'scheduleDate': '2022-07-23', 'scheduleTime': '00:40:00', 'serviceType': 'J', 'terminal': 1, 'transferPositions': None, 'schemaVersion': '4'}
Converted to DataFrame with shape: (200, 35)

Converting all_airlines from list to DataFrame...
List length: 27
First item sample: {'iata': 'MH', 'icao': 'MAS', 'nvls': 5065, 'publicName': 'Malaysia Airlines Berhad'}
Converted to DataFrame with shape: (27, 4)

============================================================
MERGING AIRLINES DATA WITH FLIGHTS
============================================================

all_flights columns: ['lastUpdatedAt', 'actualLandingTime', 'actualOffBlockTime', 'aircraftRegistration', 'aircraftType', 'baggageClaim', 'checkinAllocations', 'codeshares', 'estimatedLandingTime', 'expectedTimeBoarding', 'expectedTimeGateClosing', 'expectedTimeGateOpen', 'expectedTimeOnBelt', 'expectedSecurityFilter', 'flightDirection', 'flightName', 'flightNumber', 'gate', 'pier', 'id', 'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO', 'airlineCode', 'publicEstimatedOffBlockTime', 'publicFlightState', 'route', 'scheduleDateTime', 'scheduleDate', 'scheduleTime', 'serviceType', 'terminal', 'transferPositions', 'schemaVersion']
all_airlines columns: ['iata', 'icao', 'nvls', 'publicName']

Merge keys: all_flights['prefixICAO'] -> all_airlines['icao']

Original flights shape: (200, 35)
New merged shape: (200, 39)

First 2 rows after merge:
                   lastUpdatedAt              actualLandingTime  \
0  2022-07-23T03:51:46.126+02:00  2022-07-23T01:48:22.000+02:00
1  2022-07-24T08:04:43.696+02:00                           None

              actualOffBlockTime aircraftRegistration  \
0                           None                 None
1  2022-07-23T00:35:56.000+02:00                PHCKC

                            aircraftType      baggageClaim checkinAllocations  \
0  {'iataMain': '737', 'iataSub': '73H'}  {'belts': ['2']}               None
1  {'iataMain': '74F', 'iataSub': '74Y'}              None               None

                   codeshares           estimatedLandingTime  \
0  {'codeshares': ['KL2598']}  2022-07-23T01:48:22.000+02:00
1                        None                           None

  expectedTimeBoarding  ... scheduleDate scheduleTime serviceType terminal  \
0                 None  ...   2022-07-23     00:40:00           J      1.0
1                 None  ...   2022-07-23     00:40:00           F      NaN

  transferPositions schemaVersion  iata icao   nvls publicName
0              None             4    KL  KLM  100.0        KLM
1              None             4   NaN  NaN    NaN        NaN

[2 rows x 39 columns]

Rows with airline name matched: 0 out of 200

Final columns: ['lastUpdatedAt', 'actualLandingTime', 'actualOffBlockTime', 'aircraftRegistration', 'aircraftType', 'baggageClaim', 'checkinAllocations', 'codeshares', 'estimatedLandingTime', 'expectedTimeBoarding', 'expectedTimeGateClosing', 'expectedTimeGateOpen', 'expectedTimeOnBelt', 'expectedSecurityFilter', 'flightDirection', 'flightName', 'flightNumber', 'gate', 'pier', 'id', 'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO', 'airlineCode', 'publicEstimatedOffBlockTime', 'publicFlightState', 'route', 'scheduleDateTime', 'scheduleDate', 'scheduleTime', 'serviceType', 'terminal', 'transferPositions', 'schemaVersion', 'iata', 'nvls', 'publicName']

We saved the best for last. A flight can have multiple destinations:

![](files\2022-11-14-21-39-49.png)

So this is like with the aircraft types where you have to split up a dict into multiple columns, but now the value in one of these columns is a list. You could duplicate the row for every value in the list, but then you could argue that at that point you'll be messing up your data. Flights with multiple destinations will start showing up twice in graphs.

And for this reason we won't be going there.